### PR TITLE
[bcm283x] Fix typo in mailbox constant

### PR DESCRIPTION
**Pull request by berkus**

### CODE REVIEW

**Comment by bufferoverflow** [comment]
u-boot community does not handle PRs on GitHub, please read https://github.com/u-boot/u-boot/blob/master/README

**Comment by berkus** [comment]
I'm definitely not sending anything to mailing lists. You can live with invalid constants if you want.

**Comment by bufferoverflow** [comment]
¯\\\_(ツ)_/¯

**Comment by trini** [comment]
@berkus can I ask why?  We indeed haven't been clear enough previously that github PRs aren't how we work (I wish we could remove the feature from the repository).

**Comment by berkus** [comment]
@trini Because mailing lists are very inconvenient compared to github PRs, require special formatting, special mailing program setup and other unhandy operations. Even a simple discussion of the PR turns into "sign up to a mailing list, dig through a number of intertwined, overquoted mail messages in a very clunky interface" etc. GH PRs are designed to be easy to interact with, part of the same convenient interface, good history and visibility (not only to people who are signed up to mailing list somewhere).

**Comment by trini** [comment]
Thanks for explaining your feelings on this @berkus.  I'm tagging @agraf as he's the Pi custodian and might be interested in picking up your work at least.

**Comment by agraf** [comment]
Sure :). @berkus, could you please give me some references where the correct constant is defined in the patch description and end the commit message with a Signed-off-by line?

That way I can take the patch as you sent it, put it on the ML and apply it from there if nobody complains within a few days. That should give us the best of both work flows (github vs ML).

**Comment by berkus** [comment]
@agraf it's here https://github.com/berkus/u-boot/commit/b26467c2b55196b4536e4be69cea2691bf8465a1

**Comment by agraf** [comment]
Thanks, I sent it out as mail to the ML to give others a chance to review as well. Once that process is through, I'll pull it into the rpi queue which will then land in U-Boot proper.

Thanks a lot for the patch!

**Comment by berkus** [comment]
🙇 Thank you!

**Pull request closed without merging**
