### PR TITLE
pico-imx7d: Add support for the 2GB variant

### PR DESCRIPTION
**Pull request by Livius90**
Add the board detection mechanism to be able to support the 2GB variant.

Based on the code from TechNexion U-Boot downstream tree.

### CODE REVIEW

**Comment by Livius90** [comment]
Hi, @richard-hu and @JoeZhang-tn

We would like to add the board detection mechanism to be able to support the new 2GB variant of Technexion PICO-IMX7 SoM in u-boot mainline. Can you review our idea about it? There are two way/code what we have corrently. I made a simple refacored code based on your u-boot-tn-imx repo and there is a same code in logicaly by switch-case architect by @fabioestevam .

- Look-up table of revision detection
```C
/**********************************************
* Revision Detection
*
* DDR_TYPE_DET_1   DDR_TYPE_DET_2
*   GPIO1_12         GPIO1_13
*     0                0          1GB DDR3
*     0                1          2GB DDR3
*     1                0          512MB DDR3
*
***********************************************/
```

- Refactored code from u-boot-tn-imx repo (functions were renamed only)
```C
static bool is_gpio1_12_low(void)
{
	gpio_direction_input(IMX_GPIO_NR(1, 12));
	return !gpio_get_value(IMX_GPIO_NR(1, 12));
}

static bool is_gpio1_13_high(void)
{
	gpio_direction_input(IMX_GPIO_NR(1, 13));
	return gpio_get_value(IMX_GPIO_NR(1, 13));
}

static void ddr_init(void)
{
	if (is_gpio1_12_low()) {
		if (is_gpio1_13_high()) {
			ddrc_regs_val.addrmap0	= 0x0000001f;
			ddrc_regs_val.addrmap1	= 0x00181818;
			ddrc_regs_val.addrmap4	= 0x00000f0f;
			ddrc_regs_val.addrmap5	= 0x04040404;
			ddrc_regs_val.addrmap6	= 0x04040404;
		} else
			ddrc_regs_val.addrmap6	= 0x0f070707;
	}
	mx7_dram_cfg(&ddrc_regs_val, &ddrc_mp_val, &ddr_phy_regs_val,
		     &calib_param);
}
```

- Switch case code by @fabioestevam 
```C
static int imx7d_pico_detect_board(void)
 {
 	gpio_direction_input(IMX_GPIO_NR(1, 12));
	gpio_direction_input(IMX_GPIO_NR(1, 13));

	return gpio_get_value(IMX_GPIO_NR(1, 12)) << 1 |
	       gpio_get_value(IMX_GPIO_NR(1, 13));
}

static void ddr_init(void)
{
	switch (imx7d_pico_detect_board()) {
	case 0:
 		ddrc_regs_val.addrmap6	= 0x0f070707;
		break;
	case 1:
		ddrc_regs_val.addrmap0	= 0x0000001f;
		ddrc_regs_val.addrmap1	= 0x00181818;
		ddrc_regs_val.addrmap4	= 0x00000f0f;
		ddrc_regs_val.addrmap5	= 0x04040404;
		ddrc_regs_val.addrmap6	= 0x04040404;
		break;
	}

	mx7_dram_cfg(&ddrc_regs_val, &ddrc_mp_val, &ddr_phy_regs_val,
		     &calib_param);
}
```
@richard-hu, @JoeZhang-tn
@fabioestevam 's switch-case code can be prefered to use but can you review it? I have no access for any variants of PICO-IMX7 schematic, and we can not check that all GPIO pins are connected to a fixed high/low state in all PCB revisions/variants.

Is there was any special HW feature why needed to use a nested if statements to check 1GB then 2GB detection? Are GPIO1_12 and GPIO1_13 connected and readable well in all SoM revisions and can we get back the desired look-up table values in real for any SoMs?

**Comment by JoeZhang-tn** [comment]
Looks like the switch-case is works the same as double-if we provided.

**Comment by fabioestevam** [comment]
Hi @richard-hu and @JoeZhang-tn 

Thanks for the feedback. I will submit a formal patch to the U-Boot list.

Thanks

**Comment by richard-hu** [comment]
Thanks! @fabioestevam  @Livius90 .

**Comment by Livius90** [comment]
I would have been grateful if I could be added to the list of contributors for this commit.
https://github.com/u-boot/u-boot/commit/068027b1a0c1f445d9f4da88ab74b165f902b206

**Pull request closed without merging**
